name: docker-build

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  hadolint:
    uses: ./.github/workflows/hadolint.yml
  build:
    runs-on: ubuntu-latest
    needs:
      - hadolint
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          push: false
          tags: utopiaplanitia/kubectl:latest
