name: docker-push

on:
  push:
    branches:
      - main
      - master

jobs:
  hadolint:
    uses: ./.github/workflows/hadolint.yml
  build-and-push:
    runs-on: ubuntu-latest
    needs:
      - hadolint
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          load: true
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kubectl:ci
      - run: |
          KUBECTL_VERSION="$(docker run --rm utopiaplanitia/kubectl:ci printenv KUBECTL_VERSION)"
          echo "KUBECTL_VERSION=${KUBECTL_VERSION:?}" >> $GITHUB_ENV
      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kubectl:${{ env.KUBECTL_VERSION }}
